### ISSUE TITLE
Not compatible with Django 3.1

### ISSUE THREAD

**Issue by AnderUstarroz** [ulule/django-separatedvaluesfield#14]
Doesn't work with Django 3.1 because `django.utils` do not contain `six` anymore.

Log:
```
/Users/xx/Sites/work/xxxx/project/models.py", line 7, in <module>
    from separatedvaluesfield.models import SeparatedValuesField
  File "/Users/xx/.pyenv/versions/3.7.9/envs/xxxx/lib/python3.7/site-packages/separatedvaluesfield/models.py", line 8, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' 

```

**Comment by thoas** [comment]
Thank you for the report, you can send us a PR directly.
